version: '3.8'

services:
  redis:
    container_name: moon-redis-symbols
    ports:
      - 6380:6379
    image: redis:latest
  worker:
    container_name: moon-worker
    environment:
      - NODE_ENV=microservice
    build:
      context: ./
      dockerfile: Dockerfile.worker

  app:
    container_name: moon-worker-api
    environment:
      - NODE_ENV=microservice
    ports:
      - 3005:3005
    build:
      context: ./
      dockerfile: Dockerfile.app
