version: '3.8'

services:
  mysql:
    container_name: moon-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=cryptoapp
      - MYSQL_TCP_PORT=3306
    ports:
      - 3307:3306
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
  app:
    container_name: moon-app
    environment:
      - NODE_ENV=compose
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile.app
    depends_on:
      mysql:
        condition: service_healthy
  redis:
    container_name: moon-redis
    ports:
      - 6379:6379
    image: redis:latest

          

